Hamid
dnj/developer-recruitment pull request #13
Opened 2022-12-23 10:02 UTC by HamidNiakan

task completed

2022-12-24 12:45 UTC, yeganemehr requested changes
Hi Hamid
Thank you for participating in the challenge.
You must not change the tests, Please revert your changes.
Also put your code on correct directory like it's described on Readme.md

2022-12-24 12:50 UTC, HamidNiakan commented
چشم حتما انجام میدم

On Sat, Dec 24, 2022, 4:15 PM Amir H. Yeganemehr ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi Hamid
> Thank you for participating in the challenge.
> You must not change the tests, Please revert your changes.
> Also put your code on correct directory like it's described on Readme.md
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dnj/developer-recruitment/pull/13#pullrequestreview-1229627227>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGHWODUK54TZMPTTTFPSSZDWO3V7PANCNFSM6AAAAAATHSSCXE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-26 10:16 UTC, yeganemehr approved these changes
Thank you for following up the challenge.
I'll merge it.
HR call soon.

2022-12-26 10:16 UTC, yeganemehr commented on challenges/3/YOUR-CODE-GOES-HERE/hamidrezaNiakan/app/Http/Controllers/TravelController.php
> +					'id' => $travel->id ,
What is point of this controller if you give it travel's id and retrieve just id of the travel?
One of soft skills you need in every job you'll need is that you do tasks based on context.

2022-12-26 10:16 UTC, yeganemehr commented on challenges/3/YOUR-CODE-GOES-HERE/hamidrezaNiakan/app/Http/Controllers/TravelSpotController.php
> +		DB::commit();
You commit the transaction after you return. Tests are passed but not going to work on production.
It's a state of art!

2022-12-26 10:16 UTC, yeganemehr commented on challenges/3/YOUR-CODE-GOES-HERE/hamidrezaNiakan/app/Http/Controllers/TravelSpotController.php
> +		$this->validate($request , [
We already provide you `TravelSpotStoreRequest` to help you with validation.
This apply for all of other insert/update controllers too.

2022-12-26 10:16 UTC, yeganemehr commented on challenges/3/YOUR-CODE-GOES-HERE/hamidrezaNiakan/app/Http/Controllers/TravelController.php
> +	public function store ( TravelStoreRequest $request ) {
Authorization and policies are forgotten?

2022-12-26 10:17 UTC, merged

2022-12-26 10:20 UTC, HamidNiakan commented
سلام وقت بخیر این ها رو برطرف خواهم کردم


On Mon, Dec 26, 2022, 1:47 PM Amir H. Yeganemehr ***@***.***>
wrote:

> Merged #13 <https://github.com/dnj/developer-recruitment/pull/13> into
> master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dnj/developer-recruitment/pull/13#event-8110709569>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGHWODX67RZMBMDSSKSVNMTWPFWDVANCNFSM6AAAAAATHSSCXE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-28 06:06 UTC, HamidNiakan commented
سلام وقت بخیر
مواردی که در merge request گفته بودید رو برطرف کردم .
می خواستم ببینم نتیجه کی مشخص میشه؟

On Mon, Dec 26, 2022 at 1:50 PM Hamidreza Niakan ***@***.***>
wrote:

> سلام وقت بخیر این ها رو برطرف خواهم کردم
>
>
> On Mon, Dec 26, 2022, 1:47 PM Amir H. Yeganemehr ***@***.***>
> wrote:
>
> > Merged #13 <https://github.com/dnj/developer-recruitment/pull/13> into
> > master.
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <https://github.com/dnj/developer-recruitment/pull/13#event-8110709569>,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AGHWODX67RZMBMDSSKSVNMTWPFWDVANCNFSM6AAAAAATHSSCXE
> >
> > .
> > You are receiving this because you authored the thread.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dnj/developer-recruitment/pull/13#issuecomment-1365063709>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGHWODT232RO4NVD6KCWPNDWPFWQRANCNFSM6AAAAAATHSSCXE>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>